#!/usr/bin/awk -f

BEGIN {
	FS = "\t"
	src = "de/smallmp3/"
	dest = "de/forEncoder/"
print src
print dest
	while("cat de/validated-short.tsv" | getline)
	{
		if($4 < 0 || $5 > 0) continue
		client_id = $1
		mp3path = $2
		flacpath = mp3path
		sub(/mp3/, "flac", flacpath)
		sub(/mp3/, "txt", $2)
		sentence = $3
		# sub(/'/,"", sentence)
		up_votes = $4
		down_votes = $5
		age = $6
		gender = $7
		accent = $8
		locale = $9
		segment = $10
		if(system("test -e "src mp3path) == 0)
		{
			system("mkdir -p "dest client_id"/book0/wavs/")
			system("ffmpeg -n -i "src mp3path" "dest client_id"/book0/wavs/"flacpath)
			system("echo \'"sentence"\' >" dest client_id"/book0/wavs/"$2)
			printf("Created entries for %s\n", client_id)
		}
	}
}
